### ISSUE TITLE
Compatibility with Huawei E3531

### ISSUE THREAD

**Issue by silgon** [gammu/gammu#369]
Hello. I've been trying to make the dongle work to receive messages. (Sending is working perfectly)

My file `/etc/usb_modeswitch.d/12d1:1f01` is the following:

```
TargetVendor=0x12d1
TargetProduct= 0x1f01

MessageContent="55534243123456780000000000000011062000000100000000000000000000"
```

And my `/etc/gammu-smsdrc`is:

```
[gammu]
port=/dev/ttyUSB0
connection=at
name=huawei E3531
model = E3131

[smsd]
service = files
logfile = /var/log/ss.log
# Increase for debugging information
debuglevel = 5
ReceiveFrequency = 60
StatusFrequency = 60
CommTimeout = 60
SendTimeout = 60
LoopSleep = 10
CheckSecurity = 0
# Paths where messages are stored
inboxpath = /root/gammu/inbox/
outboxpath = /root/gammu/outbox/
sentsmspath = /root/gammu/sent/
errorsmspath = /root/gammu/error/
```

I really have no idea what to do. I've been tinkering with the files and I just do not know what to do.
Just as reference, I used `picocom -b 115200 -f n -p n -d 8 -r /dev/ttyUSB0` to test some stuff as the following:
```
AT+CMGF=1
AT+CMGS="+3300000000"
This is my message
# returns
+CMGS: 172
```
Which sends me a message perfectly well. Then, to read messages the following commands:
```
AT+CMGF=1
OK
AT+CMGL="ALL"
OK
```
I always have the same response. I also receive the following message when I send an sms to the number of the dongle.
```
+CMTI: "ME",0
```

Lastly, I add a [logfile](https://pastebin.com/RAgPfkWL).
Any ideas of what happens or what workaround could I use? Thanks.

**Comment by silgon** [comment]
As a complementary debug. I tried:
```
AT+CPMS="ME","ME","ME"
```
And every time I receive a message I receive.
```
+CMTI: "ME",0
+CMTI: "ME",0
+CMTI: "ME",0
+CMTI: "ME",0
```
I think the last `0` should be 0, the 1,2,3 and so, because it is the same place in memory. However I'm not sure because I've never used the `AT` commands before.

I also tried `AT+CPMS="SM","SM","SM"` but I get the same behavior only with `+CMTI: "ME",#NUMBER` when I receive a message and I get nothing in the list with `AT+CMGL="ALL"`as before.

**Comment by stevecohenfr** [comment]
Hi @silgon , I use the same dongle, did you fixed this ? I cannot receive SMS too :/

thanks

**Comment by silgon** [comment]
I didn't really solved it. But as a workaround I'm using gsmmodem with python. More specifically, [this example](https://github.com/faucamp/python-gsmmodem/blob/master/examples/sms_handler_demo.py) works fine for me, I receive some data and then I reply.  (this is a copy paste of a [comment in stackoverflow](https://stackoverflow.com/questions/47079324/at-commands-with-e3531-sms-disappears-after-one-second)).

**Comment by Ailothaen** [comment]
Hello,
I have the same modem and I am currently having the exact same problem: I can send SMS without any problems, but I cannot receive any (and nothing appears in the log or in the inbox upon "reception"). Has someone found solutions for this?

**Comment by stevecohenfr** [comment]
I tried the python workaround. It works fine but only when the message arrive while python-gsmmodem is running. If you start the program after received your message, it unable to read it (like no sms was on the sim memory). I tried with AT command line directly and have the same issue : +CMTI: "ME",0

So this issue does not appear to be part of gammu but maybe about the dongle (or SIM card ?). What sim card are you using ? I'm using french sim card "Free".

**Comment by silgon** [comment]
I tested also free and another company in another country. I think it was similar. My guess is that the companies store messages and you have to send some kind of code so they send you the past messages back (like when you turn off your phone for some days and you get a lot of sms). Since I'm not an expert I'm only speculating, good luck =)

**Comment by stevecohenfr** [comment]
Now it works fine for me, I don't know why :o I developed my own service using python-gsmmodem. My services work fine, I just tried gammu a last time before uninstalling it and it seems to work fine now.... I receive my SMS without problem...
I added

    atgen_setCNMI=2,0,0,2,1

to my [gammu] config, it was not working after multiple gammu-smsd restart and now it works fine. I don't know if it works because of this line or not, but it work (for the moment! 🤞)

**Comment by peykens** [comment]
I can't get any workaround working on my setup : Rpi3 with Huawei E3531
1) When I set the atgen_setCNMI in the gammu config, it doesn't seem to pick it up. In the startup of smsd, I still see AT+CNMI=2,1,0,2 popping up.
2) When I try the python script, I get timeouts after about 5sec on modem.connect(PIN)
commands = self.supportedCommands
response = self.write('AT+CLAC')

Any idea ?

**Comment by stevecohenfr** [comment]
@peykens what serial do you connect ? ttyUSB0 / ttyUSB1 / ttyUSB2 ? I tried to connect to ttyUSB2 and had a timeout, ttyUSB0 works fine. Try it.
Did you try [this script](https://github.com/faucamp/python-gsmmodem/blob/master/examples/sms_handler_demo.py) ? 

PS: Don't forget to stop gammu-smsd to release the dongle before launching the python script ;)

**Comment by peykens** [comment]
Hi @stevecohenfr ,

Thx for the quick response.

I'm using ttyUSB0 since that one is also working with gammu.
Yes, smsd is stopped and yes I use the same script, I justed renamed it to sms.py.

pi@smsgw:~/python $ python sms.py
Initializing modem...
INFO: Connecting to modem on port /dev/ttyUSB0 at 115200bps
DEBUG: write: ATZ
DEBUG: response: ['OK']
DEBUG: write: ATE0
DEBUG: response: ['OK']
DEBUG: write: AT+CFUN?
DEBUG: response: ['+CFUN: 1', 'OK']
DEBUG: write: AT+CMEE=1
DEBUG: response: ['OK']
DEBUG: write: AT+CPIN?
DEBUG: response: ['+CPIN: READY', 'OK']
DEBUG: write: AT+CLAC
Traceback (most recent call last):
  File "sms.py", line 39, in <module>
    main()
  File "sms.py", line 31, in main
    modem.connect(PIN)
  File "/home/pi/.local/lib/python2.7/site-packages/gsmmodem/modem.py", line 201, in connect
    commands = self.supportedCommands
  File "/home/pi/.local/lib/python2.7/site-packages/gsmmodem/modem.py", line 490, in supportedCommands
    response = self.write('AT+CLAC')
  File "/home/pi/.local/lib/python2.7/site-packages/gsmmodem/modem.py", line 398, in write
    responseLines = SerialComms.write(self, data + writeTerm, waitForResponse=waitForResponse, timeout=timeout, expectedResponseTermSeq=expectedResponseTermSeq)
  File "/home/pi/.local/lib/python2.7/site-packages/gsmmodem/serial_comms.py", line 135, in write
    raise TimeoutException()
gsmmodem.exceptions.TimeoutException

**Comment by stevecohenfr** [comment]
Are you using the [last python-gsmmodem version](https://github.com/babca/python-gsmmodem) ? (called python-gsmmodem-new), the faucamp's version is no longer maintained and out of date.

**Comment by peykens** [comment]
@stevecohenfr , No I was not aware of the new module.
I missed it somehow.
Just did the update and now SMS messages are arriving as expected !

Thx a lot !!!

**Comment by stevecohenfr** [comment]
Your welcome :) I spend a lot of time  to replace gammu with python-gsmmodem for my E3531.

The python exemple is just an exemple, it's incomplete. It does not read sms in the memory (if you receive a sms before starting the script). And it does not concat multiple parts sms (it will print unordered parts).
Also, as your live read sms script is running, you cannot send sms with another script because the dongle is busy. 

If you are interested I can create a gist with my python script. It quite simple but it concat big sms, read sms in memory regularly and is start a daemon that communicate with my other script to send a sms.

**Comment by peykens** [comment]
Hi @stevecohenfr,

Yes I'm very interested. I also spend a lot of time. First to get gammu working on raspberry with a GSM/GPRS addon for rpi (https://www.amazon.de/gp/product/B07L82YYCK/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1).
But I gave up on that, so I purchased the Huawei E3531.

That was communicating fine, but with gammu I encountered a lot of instabilities.

I want to setup an e2e test chain where SMS flow in involved. So I need to catch every SMS and push them on an MQTT broker.

**Comment by PilotWill** [comment]
Not sure if this helps but I've just used AT+CNMI=0,1,2,2,0 to set mode (first digit in the string is mode and set to 0) to put SMS-Deliver indications in the ME and now AT+CMGL shows received text messages on to my terminal and AT+CMGR=0 etc works as I'd hoped. Modem is Huawei E3531

**Comment by stevecohenfr** [comment]
Hey @peykens ,

I just created the gist my python-gsmmodem script :

https://gist.github.com/stevecohenfr/8d3908da4ed39169992e407261f4c0e6

Enjoy :)

**Comment by stevecohenfr** [comment]
> can I confirm that this modem is now no longer supported by gammu and that we should use python-gsmmodem ?

I cannot confirm that it no longer compatible. But there is a lot of issues with gammu and this dongle. And Gammu developer stopped maintaining this project some months ago. So I suggest you to use python-gsmmodem-new. You can use my script from gist for a complete exemple.

**Comment by Pride1922** [comment]
I'm writing here again because this thread helped me get to the solution and it might help others in the future.

I have a Huawei K4203 and I am on Ubuntu 20.04 on a Raspberry pi 4.  This is the config I used for [gammu] that allowed me to receive SMS. (Send SMS has always worked without a problem).

[gammu]
# Please configure this!
port = /dev/ttyUSB0
connection = at115200
model = at
atgen_setCNMI=0,1,2,2,0
#### DEBUGGING ######
logfile = syslog
logformat = textall

The project is a Nagios Monitoring sending SMS. Now what I wanted is to be able to answer using SMS and run  a script upon receiving a message. For example: If a device is down, I get a SMS and if I answer "ACK" I should be able to acknowledge on Nagios and stop receiving SMS's for this device.

**Comment by stevecohenfr** [comment]
> I'm writing here again because this thread helped me get to the solution and it might help others in the future.
> 
> I have a Huawei K4203 and I am on Ubuntu 20.04 on a Raspberry pi 4. This is the config I used for [gammu] that allowed me to receive SMS. (Send SMS has always worked without a problem).
> 
> ```
> [gammu]
> # Please configure this!
> port = /dev/ttyUSB0
> connection = at115200
> model = at
> atgen_setCNMI=0,1,2,2,0
> #### DEBUGGING ######
> logfile = syslog
> logformat = textall
> ```
> 
> The project is a Nagios Monitoring sending SMS. Now what I wanted is to be able to answer using SMS and run a script upon receiving a message. For example: If a device is down, I get a SMS and if I answer "ACK" I should be able to acknowledge on Nagios and stop receiving SMS's for this device.

Hi, yes thanks to the new version of gammu, you can now set atgen_setCNMI with 5 numbers instead of 4, and it fix some issues.
I'm not sure if you last paragraph is about getting help, but if yes, you should consider using RaspiSMS. It provide a panel to manage your sms, an API, and in the last version you can use hooks to catch received SMS.
With it you will be able to catch received SMS containing ACK, check if sending number is yours, check with API is last sent SMS to your number is your "device down" notification, and disable notification on Nagios Monitoring.
