### ISSUE TITLE
Crash on ToDo restore

### ISSUE THREAD

**Issue by one-more-alex** [gammu/gammu#396]
Made full backup of Sony Ericsson W800i.
Than it crash on restore on ToDos.

Gentoo Linux.
gammu-1.38.5.ebuild

Command:
gammu -s 6 restore sony-erricson.gammu.backup -yes

<pre>
#0  0x00007ffff79190bf in OBEXGEN_SetTodoLUID (s=0x7ffff5af5010, Entry=0x7ffffffbd270,
    Data=0x7ffffffbbe20 "BEGIN:VCALENDAR\r\nVERSION:1.0\r\nBEGIN:VTODO\r\nPRIORITY:2\r\nCATEGORIES:MISCEL
LANEOUS\r\nSUMMARY;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=D0=9B=D0=B5=D0=BA=D0=B0=D1=80=D1=81=D1=82=D0=
B2=D0=BE\r\nX-IRMC-LUID:000"..., Size=354)
    at /var/tmp/portage/app-mobilephone/gammu-1.38.5/work/gammu-1.38.5/libgammu/phone/obex/obexgen.c:2961

#1  0x00007ffff7919352 in OBEXGEN_SetTodo (s=0x7ffff5af5010, Entry=0x7ffffffbd270)
    at /var/tmp/portage/app-mobilephone/gammu-1.38.5/work/gammu-1.38.5/libgammu/phone/obex/obexgen.c:3043

#2  0x00007ffff788ebfc in GSM_SetToDo (s=0x7ffff5af5010, ToDo=ToDo@entry=0x7ffffffbd270)
    at /var/tmp/portage/app-mobilephone/gammu-1.38.5/work/gammu-1.38.5/libgammu/api.c:1363
#3  0x000055555558aade in Restore (argc=<optimized out>, argv=<optimized out>)
    at /var/tmp/portage/app-mobilephone/gammu-1.38.5/work/gammu-1.38.5/gammu/backup.c:1254
#4  0x00005555555867b1 in ProcessParameters (start=2, argc=6, argv=0x7fffffffd858)
    at /var/tmp/portage/app-mobilephone/gammu-1.38.5/work/gammu-1.38.5/gammu/gammu.c:1033
#5  0x0000555555566ddc in main (argc=6, argv=0x7fffffffd858)
    at /var/tmp/portage/app-mobilephone/gammu-1.38.5/work/gammu-1.38.5/gammu/gammu.c:1249
</pre>

Crash cause located at line 2961.

<pre>
   │2959            /* Check bounds */                                                                  │
   │2960            if (Entry->Location > Priv->TodoLUIDCount ||                                        │
  >│2961                            Priv->TodoLUID[Entry->Location] == NULL) {				│
   │2962                    /**                                                                         │
   │2963                     * \todo We should keep location here!                                      │
   │2964                     */                                                                         │
   │2965                    return OBEXGEN_AddTodo(s, Entry);                                           │
   │2966            }   
</pre

<pre>
(gdb) p	Priv->TodoLUID
$9 = (char **) 0x0
(gdb) p	Entry->Location
$10 = 0
</pre>

That is why it crashes in attempt to Priv->TodoLUID[0]

**Comment by one-more-alex** [comment]
Fix created in https://github.com/gammu/gammu/pull/397
Not sure if it is correct per logic of state machine, but it allowing code to finish normally.
