### ISSUE TITLE
DeleteSMS failing in 1.42.0 - The type of memory is not available or has been disabled

### ISSUE THREAD

**Issue by bohns** [gammu/gammu#551]
I compiled 1.42 and tested this. It is still failing.

sm.DeleteSMS(0,messagedata['Location'])

produces:

```
Traceback (most recent call last):
  File "./processTexts.py", line 110, in <module>
    daemon.start()
  File "/home/pi/Desktop/git/SMBCode/relay_project/Daemon.py", line 85, in start
    self.run()
  File "./processTexts.py", line 86, in run
    sm.DeleteSMS(1,messagedata['Location'])
gammu.ERR_MEMORY_NOT_AVAILABLE: {'Text': u'The type of memory is not available or has been disabled.', 'Code': 81, 'Where': 'DeleteSMS'}
```

gammu log file:

```
Fri 2020/10/23 11:11:23: [Gammu - 1.42.0]
Fri 2020/10/23 11:11:23: [Connection - "at19200"]
Fri 2020/10/23 11:11:23: [Connection index - 0]
Fri 2020/10/23 11:11:23: [Model type - ""]
Fri 2020/10/23 11:11:23: [Device - "/dev/ttyUSB1"]
Fri 2020/10/23 11:11:23: [Running on - Linux, kernel 5.4.51-v7l+ (#1333 SMP Mon Aug 10 16:51:40 BST 2020)]
Fri 2020/10/23 11:11:23: Serial device: DTR is up, RTS is up, CAR is down, CTS is down
Fri 2020/10/23 11:11:23: Setting speed to 19200
Fri 2020/10/23 11:11:23: [Module - "auto"]

...
Fri 2020/10/23 11:11:27: Entering GSM_DeleteSMS
Fri 2020/10/23 11:11:27: Location = 1, Folder = 0
Fri 2020/10/23 11:11:27: SMS folder 0 & location 1 -> ATGEN folder 1 & location 1
Fri 2020/10/23 11:11:27: Requested memory not available for reading: XX (-1238362640)
Fri 2020/10/23 11:11:27: GSM_DeleteSMS failed with error MEMORY_NOT_AVAILABLE[81]: The type of memory is not available or has been disabled.
Fri 2020/10/23 11:11:27: Leaving GSM_DeleteSMS
```

**Comment by kstuart** [comment]
@bohns this appears to be a python-gammu issue, I'm not familiar with that package however have taken a quick look. 

Could you test branch https://github.com/kstuart/python-gammu/tree/fix/deletesms and let me know if that fixes the issue, if not you'll need to open a ticket there.

**Comment by bohns** [comment]
@kstuart I got an error during the sudo ./setup.py install:

```
copying build/lib.linux-armv7l-2.7/gammu/data.py -> build/bdist.linux-armv7l/egg/gammu
byte-compiling build/bdist.linux-armv7l/egg/gammu/asyncworker.py to asyncworker.pyc
  File "build/bdist.linux-armv7l/egg/gammu/asyncworker.py", line 69
    async def init_async(self):
            ^
SyntaxError: invalid syntax
```
It continued on, this is what I have in pip now:
```
Name: python-gammu
Version: 3.1
Summary: Gammu bindings
Home-page: https://wammu.eu/python-gammu/
Author: Michal Cihar
Author-email: michal@cihar.com
License: GPLv2+
Location: /usr/local/lib/python2.7/dist-packages/python_gammu-3.1-py2.7-linux-armv7l.egg
Requires: 
Required-by: 
```
I should mention that I'm doing this on a Raspberry Pi. I ran my script again and still got the memory error.

**Comment by bohns** [comment]
Just got done converting my code to Python 3. The issue remains, so I'll open a ticket at python-gammu.

Thanks for the help. --- Steve
```

Name: python-gammu
Version: 3.1
Summary: Gammu bindings
Home-page: https://wammu.eu/python-gammu/
Author: Michal Cihar
Author-email: michal@cihar.com
License: GPLv2+
Location: /usr/local/lib/python3.7/dist-packages/python_gammu-3.1-py3.7-linux-armv7l.egg
Requires: 
Required-by: 
```

**Comment by bohns** [comment]
@kstuart I added to an existing issue.

[https://github.com/gammu/python-gammu/issues/39](url)
