### ISSUE TITLE
gammu-smsd segfault at +CREG response

### ISSUE THREAD

**Issue by TheNetworkIsDown** [gammu/gammu#734]
Several weeks ago our two gammu instances started crashing

Backtrace is this

```
Core was generated by `/usr/bin/gammu-smsd --pid=/var/run/gammu-smsd.pid --daemon'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fabc2017132 in ATGEN_GrabString () from /usr/lib64/libGammu.so.8
Missing separate debuginfos, use: zypper install gammu-smsd-debuginfo-1.39.0-bp151.3.1.x86_64
(gdb) bt
#0  0x00007fabc2017132 in ATGEN_GrabString () from /usr/lib64/libGammu.so.8
#1  0x00007fabc2017ec9 in ATGEN_ParseReply () from /usr/lib64/libGammu.so.8
#2  0x00007fabc20191c5 in ATGEN_ReplyGetNetworkLAC_CID () from /usr/lib64/libGammu.so.8
#3  0x00007fabc1fd4a74 in GSM_DispatchMessage () from /usr/lib64/libGammu.so.8
#4  0x00007fabc200fd52 in AT_StateMachine () from /usr/lib64/libGammu.so.8
#5  0x00007fabc1fd3c3c in GSM_ReadDevice () from /usr/lib64/libGammu.so.8
#6  0x00007fabc1fd3d3e in GSM_WaitForOnce () from /usr/lib64/libGammu.so.8
#7  0x00007fabc1fd3e7b in GSM_WaitFor () from /usr/lib64/libGammu.so.8
#8  0x00007fabc2015524 in ATGEN_GetNetworkInfo () from /usr/lib64/libGammu.so.8
#9  0x00007fabc1fd6152 in GSM_GetNetworkInfo () from /usr/lib64/libGammu.so.8
#10 0x00007fabc2310827 in SMSD_PhoneStatus () from /usr/lib64/libgsmsd.so.8
#11 0x00007fabc2310a72 in SMSD_SendSMS () from /usr/lib64/libgsmsd.so.8
#12 0x00007fabc231170f in SMSD_MainLoop () from /usr/lib64/libgsmsd.so.8
#13 0x00005603ce577c28 in main ()
```

Modem is 4G LTE Modem ConiuGo RS232 - Model LE910-EU V2

With debuglog at 255 the following is the final output

```
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: RECEIVED frame type 0x00/length 0x2D/45
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: 41A|54T|2B+|43C|52R|45E|47G|3F?|0D |0D |0A |2B+|43C|52R|45E|47G AT+CREG?...+CREG
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: 3A:|20 |322|2C,|311|2C,|22"|300|42B|2C,|22"|300|311|300|300|377 : 2,1,"0B,"01007
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: 300|311|22"|2C,|377|0D |0A |0D |0A |4FO|4BK|0D |0A              01",7....OK..
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: Network LAC & CID & state received
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: Parsing +CREG: 2,1,"0B,"0100701",7 with +CREG: @i, @i, @r, @r, @i
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: Parsed int 2
Wed 2022/08/24 03:52:24 gammu-smsd[5060]: gammu: Parsed int 1
DEAD
```

Looking at the rest of the logs, usually at this point we have
```
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Getting packet network LAC and CID and state
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: SENDING frame type 0x00/length 0x0A/10
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 41A|54T|2B+|43C|47G|52R|45E|47G|3F?|0D                          AT+CGREG?.
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 1 "AT+CGREG?"
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 2 "+CGREG: 2,1,"0BBE","0100701",7,"00""
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 3 "OK"
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Checking line: OK
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: AT reply state: 1
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: RECEIVED frame type 0x00/length 0x37/55
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 41A|54T|2B+|43C|47G|52R|45E|47G|3F?|0D |0D |0A |2B+|43C|47G|52R AT+CGREG?...+CGR
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 45E|47G|3A:|20 |322|2C,|311|2C,|22"|300|42B|42B|45E|22"|2C,|22" EG: 2,1,"0BBE","
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 300|311|300|300|377|300|311|22"|2C,|377|2C,|22"|300|300|22"|0D  0100701",7,"00".
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: 0A |0D |0A |4FO|4BK|0D |0A                                      ...OK..
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Network LAC & CID & state received
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Parsing +CGREG: 2,1,"0BBE","0100701",7,"00" with +CGREG: @i, @i, @r, @r, @i, @r
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Parsed int 2
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Parsed int 1
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Grabbed string from reply: "0BBE" (parsed 6 bytes)
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Parsed raw string "0BBE"
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Grabbed string from reply: "0100701" (parsed 9 bytes)
Wed 2022/08/24 19:24:10 gammu-smsd[18027]: gammu: Parsed raw string "0100701"
...
```

**Comment by TheNetworkIsDown** [comment]
We were running Gammu inside a VM.
Turns out the update from ESXi 6.x to 7.x seems to have introduced this problem.
Probably the serial connections on ESXi are no longer stable.
We have moved to a hardware appliance.
